[package]
name = "cpchain-rust-sdk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.21.2"
web3 = "0.18.0"
cpc={version="0.1.0", path="./cpc"}
